# Unbloarchy environment (UNBLOARCHY_PATH + PATH), needed even for non-interactive shells
bootstrap=/usr/share/unbloarchy/default/bash/env-bootstrap
[[ -r $bootstrap ]] || bootstrap=/usr/share/omarchy/default/bash/env-bootstrap
[[ ! -r $bootstrap ]] || source "$bootstrap"
unset bootstrap

# If not running interactively, don't do anything else (leave this above the rc source)
[[ $- != *i* ]] && return

# All the default Unbloarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source "$UNBLOARCHY_PATH/default/bash/rc"

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
