#!/bin/bash

set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=${1:-$(cd -- "$script_dir/../.." && pwd)}
bin_dir="$repo_root/bin"
marker="# Generated by generate-compat-shims.sh; do not edit."

if [[ ! -d $bin_dir || ! -x $bin_dir/unbloarchy || ! -x $bin_dir/unbloarchy-security-functions ]]; then
  echo "Error: expected Unbloarchy binaries were not found in $bin_dir." >&2
  exit 1
fi

shopt -s nullglob
sources=("$bin_dir"/unbloarchy-*)
expected=(omarchy)
declare -A expected_set=( [omarchy]=1 )

for source in "${sources[@]}"; do
  [[ -f $source && -x $source ]] || continue
  name=${source##*/}

  case "$name" in
    unbloarchy-security-functions|unbloarchy-dev-font)
      continue
      ;;
  esac

  alias="omarchy-${name#unbloarchy-}"
  expected+=("$alias")
  expected_set["$alias"]=1
done

expected+=(omarchy-security-functions omarchy-dev-font)
expected_set[omarchy-security-functions]=1
expected_set[omarchy-dev-font]=1

# Refuse an unmanaged conflict before changing any generated output.
for alias in "${expected[@]}"; do
  target="$bin_dir/$alias"
  if [[ -e $target || -L $target ]]; then
    if [[ ! -f $target || -L $target ]] || ! grep -Fqx -- "$marker" "$target"; then
      echo "Error: refusing to overwrite unmanaged compatibility path: $target" >&2
      exit 1
    fi
  fi
done

write_shim() {
  local target="$1"
  local body="$2"
  local temporary

  temporary=$(mktemp "$bin_dir/.compat-shim.XXXXXXXX")
  printf '%s\n' "$body" >"$temporary"
  chmod 0755 "$temporary"
  mv -f -- "$temporary" "$target"
}

write_shim "$bin_dir/omarchy" "#!/bin/bash
$marker
exec \"\${BASH_SOURCE[0]%/*}/unbloarchy\" \"\$@\""

for source in "${sources[@]}"; do
  [[ -f $source && -x $source ]] || continue
  name=${source##*/}

  case "$name" in
    unbloarchy-security-functions|unbloarchy-dev-font)
      continue
      ;;
  esac

  alias="omarchy-${name#unbloarchy-}"
  write_shim "$bin_dir/$alias" "#!/bin/bash
$marker
exec \"\${BASH_SOURCE[0]%/*}/$name\" \"\$@\""
done

write_shim "$bin_dir/omarchy-security-functions" "#!/bin/bash
$marker
source \"\${BASH_SOURCE[0]%/*}/unbloarchy-security-functions\""

write_shim "$bin_dir/omarchy-dev-font" "#!/usr/bin/python3
$marker
import os
import runpy

runpy.run_path(
    os.path.join(os.path.dirname(os.path.realpath(__file__)), 'unbloarchy-dev-font'),
    run_name='__main__',
)"

# Remove only stale shims carrying our marker. Never delete an unmanaged file.
for target in "$bin_dir"/omarchy "$bin_dir"/omarchy-*; do
  [[ -f $target && ! -L $target ]] || continue
  grep -Fqx -- "$marker" "$target" || continue
  alias=${target##*/}
  [[ -n ${expected_set[$alias]:-} ]] || rm -f -- "$target"
done
