#!/bin/bash

set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=${1:-$(cd -- "$script_dir/../.." && pwd)}
bin_dir="$repo_root/bin"
marker="# Generated by generate-compat-shims.sh; do not edit."
compat_bootstrap='if [[ -z ${UNBLOARCHY_PATH:-} ]]; then
  if [[ -n ${OMARCHY_PATH:-} ]]; then
    UNBLOARCHY_PATH=$OMARCHY_PATH
  elif [[ -f /etc/omarchy.conf ]]; then
    . /etc/omarchy.conf
    UNBLOARCHY_PATH=${OMARCHY_PATH:-/usr/share/omarchy}
  else
    bin_dir=${BASH_SOURCE[0]%/*}
    if [[ $bin_dir == /usr/bin || $bin_dir == /usr/share/omarchy/bin ]]; then
      UNBLOARCHY_PATH=/usr/share/omarchy
    else
      UNBLOARCHY_PATH=$(cd -- "$bin_dir/.." && pwd)
    fi
  fi
fi
export UNBLOARCHY_PATH'
is_generated_compat() {
  local target=$1

  if [[ -L $target ]]; then
    case $(readlink "$target") in
      .omarchy-compat|.omarchy-security-functions|.omarchy-dev-font) return 0 ;;
    esac
    return 1
  fi

  [[ -f $target ]] && grep -Fqx -- "$marker" "$target"
}

if [[ ! -d $bin_dir || ! -x $bin_dir/unbloarchy || ! -x $bin_dir/unbloarchy-security-functions ]]; then
  echo "Error: expected Unbloarchy binaries were not found in $bin_dir." >&2
  exit 1
fi

shopt -s nullglob
sources=("$bin_dir"/unbloarchy-*)
expected=(omarchy)
declare -A expected_set=( [omarchy]=1 )

for source in "${sources[@]}"; do
  [[ -f $source && -x $source ]] || continue
  name=${source##*/}

  case "$name" in
    unbloarchy-security-functions|unbloarchy-dev-font)
      continue
      ;;
  esac

  alias="omarchy-${name#unbloarchy-}"
  expected+=("$alias")
  expected_set["$alias"]=1
done

expected+=(omarchy-security-functions omarchy-dev-font)
expected_set[omarchy-security-functions]=1
expected_set[omarchy-dev-font]=1

# Refuse an unmanaged conflict before changing any generated output.
for alias in "${expected[@]}"; do
  target="$bin_dir/$alias"
  if [[ -e $target || -L $target ]]; then
    if ! is_generated_compat "$target"; then
      echo "Error: refusing to overwrite unmanaged compatibility path: $target" >&2
      exit 1
    fi
  fi
done

write_file() {
  local target="$1"
  local body="$2"
  local temporary

  if [[ -e $target || -L $target ]]; then
    if ! is_generated_compat "$target"; then
      echo "Error: refusing to overwrite unmanaged compatibility path: $target" >&2
      exit 1
    fi
    rm -f -- "$target"
  fi

  temporary=$(mktemp "$bin_dir/.compat-shim.XXXXXXXX")
  printf '%s\n' "$body" >"$temporary"
  chmod 0755 "$temporary"
  mv -f -- "$temporary" "$target"
}

write_file "$bin_dir/omarchy" "#!/bin/bash
$marker
$compat_bootstrap
exec \"\${BASH_SOURCE[0]%/*}/unbloarchy\" \"\$@\""

for source in "${sources[@]}"; do
  [[ -f $source && -x $source ]] || continue
  name=${source##*/}

  case "$name" in
    unbloarchy-security-functions|unbloarchy-dev-font)
      continue
      ;;
  esac

  alias="omarchy-${name#unbloarchy-}"
  write_file "$bin_dir/$alias" "#!/bin/bash
$marker
$compat_bootstrap
exec \"\${BASH_SOURCE[0]%/*}/$name\" \"\$@\""
done

write_file "$bin_dir/omarchy-security-functions" "#!/bin/bash
$marker
source \"\${BASH_SOURCE[0]%/*}/unbloarchy-security-functions\""

write_file "$bin_dir/omarchy-dev-font" "#!/usr/bin/python3
$marker
import os
import runpy

runpy.run_path(
    os.path.join(os.path.dirname(os.path.realpath(__file__)), 'unbloarchy-dev-font'),
    run_name='__main__',
)"

# The upstream package recipes select a small set of defaults by their former
# filenames. Keep only those exact source paths available as relative links;
# unrelated identifiers such as window classes and skill names must not be
# rewritten into extra compatibility files.
legacy_defaults=(
  default/uwsm/env.d/10-omarchy
  default/environment.d/10-omarchy-fcitx.conf
  default/fontconfig/conf.avail/50-omarchy.conf
  default/systemd/user/omarchy-sleep-lock.service
  default/systemd/user/omarchy-recover-internal-monitor.service
  default/systemd/user/omarchy-migrate-notify.service
  default/systemd/user/omarchy-tailscale-receive.service
  default/systemd/user/omarchy-fcitx5.service
  default/systemd/user/omarchy-crash-watch.service
  default/systemd/user/omarchy-brightness-keyboard-auto.service
  default/systemd/zram-generator.conf.d/90-omarchy.conf
  default/systemd/system/plocate-updatedb.service.d/10-omarchy.conf
  default/sddm/omarchy
  default/wayland-sessions/omarchy.desktop
  default/fonts/omarchy/omarchy.ttf
  default/libalpm/hooks/00-omarchy-update-guard.hook
  default/libalpm/hooks/10-omarchy-hyprland-reload-pause.hook
  default/libalpm/hooks/90-omarchy-hyprland-reload-resume.hook
  default/libalpm/hooks/00-omarchy-platform-guard.hook
  default/libalpm/scripts/omarchy-platform-guard
)

for relative in "${legacy_defaults[@]}"; do
  legacy="$repo_root/$relative"
  current="$repo_root/${relative//omarchy/unbloarchy}"
  [[ -e $current && ! -e $legacy && ! -L $legacy ]] || continue

  mkdir -p "${legacy%/*}"
  if [[ -d $current ]]; then
    cp -a -- "$current" "$legacy"
  else
    target=$(realpath --relative-to="${legacy%/*}" "$current")
    ln -s "$target" "$legacy"
  fi
done

# Remove only stale shims carrying our marker. Never delete an unmanaged file.
for target in "$bin_dir"/omarchy "$bin_dir"/omarchy-*; do
  [[ -e $target || -L $target ]] || continue
  alias=${target##*/}
  [[ -z ${expected_set[$alias]:-} ]] || continue

  if is_generated_compat "$target"; then
    rm -f -- "$target"
  fi
done

for target in "$bin_dir"/.omarchy-compat "$bin_dir"/.omarchy-security-functions \
  "$bin_dir"/.omarchy-dev-font; do
  [[ -f $target ]] || continue
  grep -Fqx -- "$marker" "$target" || continue
  rm -f -- "$target"
done
